---
- hosts: all
  vars:
    docker_network: vault_net
    user: azureuser
    consul_servers:
      - consul-a
      - consul-b
      - consul-c
    consul_image_name: my-consul
  gather_facts: no
  remote_user: "{{user}}"
  become: no
  tasks:

  - name: Create persistent storage directory for Consul servers
    file:
      path: "~/consul-storage/{{item}}"
      state: directory
      owner: "{{user}}"
      group: "{{user}}"
      mode: 0775
    loop: "{{consul_servers}}"

  - name: Build a Consul image
    docker_image:
      build:
        path: ~/consul-build #Dockerfile for Consul build should be in user dir/ansible-build subfolder
      name: "{{consul_image_name}}"
      tag: v1
      force_source: yes
      #push: yes
      source: build
    #delegate_to: 127.0.0.1
    #become: no

  - name: Create a docker network
    docker_network:
      name: "{{ docker_network }}"
  
  - name: Now create a Consul Docker Container from the image
    docker_container:
      name: "{{ item }}"
      image: "{{consul_image_name}}:v1"
      state: started
      restart_policy: unless-stopped
      networks:
        - name: "{{ docker_network }}"
  #    ports:
  #      - "7500:7500"
  #      - "7300:7300"
  #      - "7301:7301"
      volumes:
        - "~/consul/{{item}}.hcl:/etc/consul/consul.hcl"
        - "~/consul-storage/{{item}}/:/opt/consul-storage"
        # - /opt/test-static/nginx/ssl/:/etc/nginx/ssl
        # - /opt/test-static/public/:/opt/test-static/public
    loop: "{{consul_servers}}"